---
baseURL: ''
title: Quire Starter
languageCode: en-us
theme: default
publishDir: site
footnoteReturnLinkContents: "↩"
metaDataFormat: yaml
GoogleAnalytics: ''
pluralizeListTitles: true
disableKinds:
- home
- section
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  searchEnabled: true
  licenseIcons: true
  pageLabelDivider: ". "
  citationPageLocationDivider: ", "
  contributorByline: name-title
  displayBiblioShort: true
  biblioHeading: Bibliography
  imageDir: img
  tocType: full
  menuType: full
  prevPageButtonText: Back
  nextPageButtonText: Next
  entryPageSideBySideLayout: true
  entryPageObjectLinkText: View in Collection
  figureLabelLocation: on-top
  figureModal: true
  figureModalIcons: true
  figureZoom: true
  citationPopupStyle: text
